apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} #from RELEASE NAME
spec:
  selector:
    {{- include "app.labels" . | nindent 4 }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  # type: {{- if .Values.ingress.enabled }} ClusterIP {{- else }} LoadBalancer {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodePort }}
