apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: "BUCKET_NAME"
      endpoint: "s3.REGION_NAME.amazonaws.com"
      region: "REGION_NAME"
      access_key: "ACCESS_KEY"
      secret_key: "SECRET_KEY"
      insecure: false
      signature_version2: false
