apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-sidecar
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-sidecar
  template:
    metadata:
      labels:
        app: thanos-sidecar
    spec:
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.32.1
        args:
        - sidecar
        - --tsdb.path=/prometheus
        - --prometheus.url=http://monitoring-stack-kube-prometheus-prometheus.monitoring.svc:9090
        - --objstore.config-file=/etc/thanos/objstore.yml
        - --log.level=info
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
        - name: objstore-config
          mountPath: /etc/thanos
      volumes:
      - name: prometheus-data
        emptyDir: {}
      - name: objstore-config
        configMap:
          name: thanos-objstore
