apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore
  namespace: monitoring
data:
  objstore.yml: |
    type: S3
    config:
      bucket: my-thanos-bucket
      endpoint: s3.amazonaws.com
      access_key: <AWS_ACCESS_KEY_ID>
      secret_key: <AWS_SECRET_ACCESS_KEY>
      region: us-east-1
      insecure: false
