apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: thanos-query
  replicas: 1
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.39.0
        args:
          - query
          - --http-address=0.0.0.0:9090
          - --grpc-address=0.0.0.0:10901
          - --endpoint=dnssrv+_grpc._tcp.prometheus-server.monitoring.svc.cluster.local
          - --endpoint=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local
        ports:
          - name: http
            containerPort: 9090
          - name: grpc
            containerPort: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  selector:
    app: thanos-query
  ports:
    - name: http
      port: 9090
      targetPort: 9090
    - name: grpc
      port: 10901
      targetPort: 10901
